// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const projectId = "krsytinnruhylcvglfzp";
const password = "ditchtheweatherapp";
const poolHost = "aws-1-ap-south-1.pooler.supabase.com";
const poolPort = 6543;
const poolUser = `postgres.${projectId}`; // Required for Supabase PgBouncer
const defaultPoolUrl = `postgresql://${poolUser}:${password}@${poolHost}:${poolPort}/postgres?pgbouncer=true&connection_limit=1&sslmode=require`;
const datasourceUrl = process.env.PRISMA_DATASOURCE_URL ?? defaultPoolUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});

